Projeto remodelado Reconciliacao
LidianeCarv/reconciliacao pull request #5
Opened 2024-03-21 16:52 UTC by LidianeCarv

Atualização do projeto para Reconciliacao.

2024-03-28 19:20 UTC, LidianeCarv commented on database-docker/init.sql
https://github.com/LidianeCarv/reconciliacao/blob/95c92c1983cf813fb87f01143fbe7f2674fc4738/database-docker/init.sql#L3-L7

2024-03-28 19:42 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/ExtratoBanco.java
> +
https://github.com/LidianeCarv/reconciliacao/blob/2af63632e08f277f024a2c7f0ec3df35f5a16df9/src/main/java/contas/model/reconciliacao/Reconciliacao.java#L7-L9

2024-03-28 19:43 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/ExtratoBanco.java
> +    public float saldo;
https://github.com/LidianeCarv/reconciliacao/blob/2af63632e08f277f024a2c7f0ec3df35f5a16df9/src/main/java/contas/model/reconciliacao/ExtratoBanco.java#L19-L21

2024-03-28 19:44 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/ExtratoBanco.java
> +    public float saldo;
Feito:   ```
 private int id;
    private LocalDate dataLancamento;
    private String historico;
    private String descricao;
```

2024-03-28 19:45 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/MovimentacaoFinanceira.java
> +    public String descricao;
`private int id;
    private TipoMovimentacaoFinanceira tipo;
    private float valor;`

2024-03-28 19:45 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/MovimentacaoReserva.java
> +    public float ganhosBrutos;
```
private int id;
    private String tipo;
    private String origem;
```

2024-03-28 19:46 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/Reconciliacao.java
> +    LocalDate data;
> `    private Long id;
    private LocalDate data;
    private String notas;`

2024-03-28 19:46 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/Reconciliacao.java
> +    MovimentacaoFinanceira movimentacaoFinanceira;
`@ManyToOne
    private ExtratoBanco extratoBanco;

    @ManyToOne
    private MovimentacaoReserva movimentacaoReserva;`

2024-03-28 19:47 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/ReconciliacaoDTO.java
> +    MovimentacaoFinanceira movimentacaoFinanceira;
`private Long id;
    private LocalDate data;
    private String notas;
    private ExtratoBanco extratoBanco;`

2024-03-28 19:48 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/ReconciliacaoService.java
> +    }
`   //Método mantido para servir de modelo`

2024-03-28 20:50 UTC, joaopaulo90 requested changes

2024-03-28 20:50 UTC, joaopaulo90 commented on database-docker/init.sql
> +	CONSTRAINT fko19echlfvqevuemcifvtdiv21 FOREIGN KEY (movimentacao_reserva_id) REFERENCES reconciliacao.movimentacao_reserva(id)
referenciam tabelas que ainda não foram criadas
tem que mudar a ordem de criação das tabelas

2024-03-28 20:50 UTC, joaopaulo90 commented on database-docker/init.sql
> +	id serial4 NOT NULL,
o `id` da tabela de reconciliação é `bigserial` porém as demais são `serial4`. por que?

2024-03-28 20:50 UTC, joaopaulo90 commented on database-docker/init.sql
> +	valor float4 NOT NULL,
todas colunas em todas as tabelas estão como `NULL`
tem que avaliar quais devem ser `NOT NULL`
esta alteração tem que ser feita na classe java de maneira que a coluna seja gerada de acordo

2024-03-28 20:50 UTC, joaopaulo90 commented on src/main/java/contas/model/reconciliacao/ExtratoBanco.java
> +* a entrada e saída referente às reservas */
```suggestion
/* Registro de extrato bancário da conta bancária utilizada para recebimentos, despesas e retiradas relacionadas a hospedagem
*/
```

2024-03-28 20:50 UTC, joaopaulo90 commented on src/main/java/contas/model/reconciliacao/MovimentacaoFinanceira.java
> +* retiradas, as despesas e o recebimento de reservas por fora. */
```suggestion
/* Movimentação financeira sob controle dos anfitriões, ou seja, saída ou entrada na conta bancária decorrentes diretamente de ação do anfitrião. Por exemplo, uma pagamento de conta de água da hospedagem, ou despesas como compra de papel higiênico ou retirada de lucro. Um exemplo de movimentação bancária que não se enquadra aqui: recebimento de pix do airbnb ou de cliente, pois não são originários de ações dos anfitriões.
*/
```

2024-03-28 20:50 UTC, joaopaulo90 commented on src/main/java/contas/model/reconciliacao/MovimentacaoReserva.java
> +/* Vai receber o histórico de reservas do Airbnb e do Booking */
```suggestion
/* Reserva do Airbnb, Booking ou direta (sem intermediários) */
```

2024-03-28 20:50 UTC, joaopaulo90 commented on src/main/java/contas/model/reconciliacao/Reconciliacao.java
> +
```suggestion
/* Reconciliacao entre movimentação bancária e uma das opções:
- reserva 
- movimentação financeira
*/

```

2024-03-28 20:50 UTC, joaopaulo90 commented on src/main/java/contas/model/reconciliacao/TipoMovimentacaoFinanceira.java
> +* despesas com as casas e RECEBIMENTO para valores recebidos em geral. */
```suggestion
/* Tipificacao de MovimentaçãoFinanceira.
* - RETIRADA: retirada de lucro
* - DESPESA: despesas do negócio
* - RECEBIMENTO: recebimento plataforma de hospedagem ou cliente
 */
```

2024-03-29 18:23 UTC, LidianeCarv commented on database-docker/init.sql
> +	valor float4 NOT NULL,
https://github.com/LidianeCarv/reconciliacao/blob/8fffb6b68dc4b9a2b58cc032f4ef41f63827d859/src/main/java/contas/model/reconciliacao/MovimentacaoFinanceira.java#L22-L28

2024-03-29 18:23 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/ExtratoBanco.java
> +* a entrada e saída referente às reservas */
https://github.com/LidianeCarv/reconciliacao/blob/8fffb6b68dc4b9a2b58cc032f4ef41f63827d859/src/main/java/contas/model/reconciliacao/ExtratoBanco.java#L10-L11

2024-03-29 18:24 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/MovimentacaoFinanceira.java
> +* retiradas, as despesas e o recebimento de reservas por fora. */
https://github.com/LidianeCarv/reconciliacao/blob/8fffb6b68dc4b9a2b58cc032f4ef41f63827d859/src/main/java/contas/model/reconciliacao/MovimentacaoFinanceira.java#L8-L12

2024-03-29 18:24 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/MovimentacaoReserva.java
> +/* Vai receber o histórico de reservas do Airbnb e do Booking */
https://github.com/LidianeCarv/reconciliacao/blob/8fffb6b68dc4b9a2b58cc032f4ef41f63827d859/src/main/java/contas/model/reconciliacao/MovimentacaoReserva.java#L10

2024-03-29 18:25 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/Reconciliacao.java
> +
https://github.com/LidianeCarv/reconciliacao/blob/8fffb6b68dc4b9a2b58cc032f4ef41f63827d859/src/main/java/contas/model/reconciliacao/Reconciliacao.java#L8-L11

2024-03-29 18:25 UTC, LidianeCarv commented on src/main/java/contas/model/reconciliacao/TipoMovimentacaoFinanceira.java
> +* despesas com as casas e RECEBIMENTO para valores recebidos em geral. */
https://github.com/LidianeCarv/reconciliacao/blob/8fffb6b68dc4b9a2b58cc032f4ef41f63827d859/src/main/java/contas/model/reconciliacao/TipoMovimentacaoFinanceira.java#L3-L7

2024-03-29 18:28 UTC, joaopaulo90 approved these changes

2024-03-29 19:30 UTC, LidianeCarv commented on database-docker/init.sql
> +	CONSTRAINT fko19echlfvqevuemcifvtdiv21 FOREIGN KEY (movimentacao_reserva_id) REFERENCES reconciliacao.movimentacao_reserva(id)
https://github.com/LidianeCarv/reconciliacao/blob/933cb6068fb693b366f0803fd17541fdae77c08b/database-docker/init.sql#L39-L50

2024-03-29 19:30 UTC, LidianeCarv commented on database-docker/init.sql
> +	id serial4 NOT NULL,
Todas têm as mesmas indormações, tanto de `notations` quanto de tipo de dado.

2024-03-29 19:31 UTC, joaopaulo90 approved these changes

2024-03-29 19:35 UTC, merged